config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get 'last', to: 'cart#last'
  get 'checkout', to: 'cart#checkout'
  get 'final', to: 'cart#final'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :sessions
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    # orderables.to_a.sum { |orderable| orderable.total }
    orderables.to_a.sum(&:total)
  end

  def total_items
    sum = 0
    orderables.each do |orderable|
      sum += orderable.quantity
    end
    sum
  end

  def update_quantity
    orderables.each do |ord|
      product = Product.find_by(id: ord.product_id)
      new_quantity = product.stock - ord.quantity
      product.stock = new_quantity
      product.save
    end
  end

end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.value * quantity
  end
  
end

app/models/product.rb
class Product < ApplicationRecord

  has_rich_text :description
  has_many_attached :images
  has_many :orderables
  has_many :carts, through: :orderables
  
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password validations: false

  before_create { generate_token(:auth_token) }
  
  validates_uniqueness_of :username
  validates :username, presence: {message: "não pode estar em branco."}, length: { in: 4..14, message: 'tem que ter entre 4 a 14 caracteres.' }, uniqueness: {message: 'já em uso.'}
  validates :email, presence: {message: "não pode estar em branco."}, uniqueness: {message: 'já em uso.'}
  validates :password, presence: {message: "não pode estar em branco."}, length: { in: 3..6, message: 'tem que ter entre 3 a 6 caracteres.' }

  HUMANIZED_ATTRIBUTES = {
  :email => "Email",
  :password => "Senha", 
  :username => "Usuário",
  }

  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_render_cart
  # before_action :initialize_cart
  before_action :cart_by_user

  private

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])
    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end

  def cart_by_user
    if current_user.nil?
      session[:cart_id] = nil
    else
      @cart ||= Cart.find_by(id: session[:cart_id])
      if @cart.nil?
        @cart = Cart.create
        session[:cart_id] = @cart.id
      end
    end
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :check_user
  
  def show
    @render_cart = false
  end

  def checkout
  end

  def last
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity:)
    elsif quantity <= 0 
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity:)
    end
    if params[:from].to_i == 1
      return redirect_to cart_path
    else
    respond_to do |format|

      # format.html { redirect_to cart_path }

        format.turbo_stream do
          render turbo_stream: [turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart }),
          turbo_stream.replace('cart_qtty', partial: 'layouts/cart_qtty', locals: { cart: @cart })]
        end
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart }),
        turbo_stream.replace('cart_qtty', partial: 'layouts/cart_qtty', locals: { cart: @cart })]
        
      end
    end
  end

  def final
    @cart.update_quantity
    @cart.orderables.each do |ord|
      ord.destroy
    end
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to last_url }
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart_qtty', partial: 'layouts/cart_qtty', locals: { cart: @cart })]
      end
    end
  end

  private

  def check_user
    if current_user.nil?
      flash[:danger] = "É necessário estar logado."
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController  

  def index
    @products = Product.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id)
    else
      flash[:danger] = "ocorreu um erro"
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :keywords, :value, :stock, :sale, :sale_price, images: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      flash[:success] = "Sessão iniciada com sucesso."
      redirect_to root_url
    else
      flash[:warning] = "Usuário ou senha inválidos."
      redirect_to login_path
    end
  end
  
  def destroy
    cookies.delete(:auth_token)
    flash[:success] = "Sessão encerrada com sucesso."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      cookies[:auth_token] = @user.auth_token
      flash[:success] = "Logado com sucesso."
      redirect_to root_url
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
    end
  end
  
end


private

  def user_params
    params.require(:user).permit(:auth_token, :username, :email, :password, :password_confirmation, :admin, :fullname)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  
  def cart_total
    if @cart.nil?
      return
    else
      if @cart.total_items > 0
        return @cart.total_items
      else
        return 0
      end
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def has_img?(product_description)
    content = rich_text(product_description)
    img_tags = content.scan(/<img.*?src=["'](.*?)["'].*?>/)
    if !img_tags[0].nil?
      return true
    else
      return false
    end
  end


  def return_img(product_description)
    content = rich_text(product_description)
    img_tags = content.scan(/<img.*?src=["'](.*?)["'].*?>/)
    if !img_tags[0].nil?
      Rails.logger.debug("img #{img_tags[0][0]}")
      image_url = img_tags[0][0]
      image_tag(image_url, class: "resize")
    end
  end

  def rich_text(rich_text_object)
    rich_text_object.to_s
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><% blob.filename %></span>
      <span class="attachment__size"><% number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_alert.html.erb
<div class="notice">
  <% flash.each do |key, value| %>
    <div id="notice" class="alert alert-dismissible fade show alert-<%= key %>">
    <% if key == "danger" %>
      <i class="bi bi-exclamation-triangle-fill ico-<%= key %>"></i> 
    <% elsif key == "success" %>
      <i class="bi bi-check-square-fill ico-<%= key %>"></i> 
    <% elsif key == "warning" %>
      <i class="bi bi-cone-striped ico-<%= key %>"></i> 
    <% end %>
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <div class="m-3">
    <% if @cart.orderables.count > 0 %>
      <%= render "cart/orderables" %>
    <% else %>
      <div class="m-lg-3 p-3 border shadow white-bkg">
        <p>Nenhum produto em seu carrinho.</p>
        <%= link_to "Voltar à página inicial", root_path, class:"btn btn-outline-primary btn-sm" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/cart/_orderables.html.erb
<div class="container">
  <div class="m-lg-3 p-3 border shadow white-bkg">
    <div>
      <%= render partial: "alert" %>
      <h2><i class="bi bi-cart4"></i> Carrinho de compras</h2>
      <% @cart.orderables.each do |orderable| %>
        <% product = orderable.product %>
        <div id="<%= "cart-#{product.id}" %>">
          <div class="row">
            <div class="col-sm">        
              <%= product.title %>
            </div>
            <div class="col-sm">
              <%= number_to_currency(product.value, unit: "R$ ", separator: ",", delimiter: "") %>
            </div>
            <div class="col-sm-4">
              <%= form_with(url: cart_add_path)  do |f| %>
                <%= f.hidden_field :id, value: product.id %>
                
                  <%= f.label :quantity, "Quantidade", class: "form-label" %>
                  <%= f.number_field :quantity, value: orderable.quantity, style: "width: 4em;" %>
                <%= f.submit "Alterar", class: "btn btn-outline-primary mb-1 btn-sm" %>
              <% end %>
            </div>

            <div class="col-sm text-center">
              <%= form_with(url: cart_remove_path)  do |f| %>
                <%= f.hidden_field :id, value: orderable.id %>
                <div class="actions"><%= f.submit "Remover", class: "btn btn-outline-primary mb-1 btn-sm" %></div>
              <% end %>
            </div>
          </div>
        <% end %>
        <p>Total: <%= number_to_currency(@cart.total, unit: "R$ ", separator: ",", delimiter: "") %></p>
        <%= link_to "Continuar comprando", root_path, class:"btn btn-outline-primary btn-sm" %>
        <%= link_to "Checkout", checkout_path, class:"btn btn-outline-primary btn-sm" %>
    </div>    
  </div>
</div>

app/views/cart/checkout.html.erb
<div class="container">
  <div class="m-lg-3 p-3 border shadow white-bkg">
    <div>
      <%= render partial: "alert" %>
      <h2><i class="bi bi-bag-dash"></i> Checkout</h2>
      <% @cart.orderables.each do |orderable| %>
        <% product = orderable.product %>
        <div id="<%= "cart-#{product.id}" %>">
          <div class="row">
            <div class="col-sm">        
              <%= product.title %>
            </div>
            <div class="col-sm">
              <%= number_to_currency(product.value, unit: "R$ ", separator: ",", delimiter: "") %>
            </div>
          </div>
        <% end %>
        <div class="row">
          <div class="col-sm">
            Total da compra
          </div>
          <div class="col-sm">
            <%= number_to_currency(@cart.total, unit: "R$ ", separator: ",", delimiter: "") %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            Valor do frete
          </div>
          <div class="col-sm">
            R$ 50,00
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <strong>Total</strong>
          </div>
          <div class="col-sm">
            <strong><%= number_to_currency((@cart.total + 50.0), unit: "R$ ", separator: ",", delimiter: "") %></strong>
          </div>
        </div>
        <div class="row" style="margin-top:20px;">
          <div class="col-sm">
            <%= link_to "Finalizar compra", final_path, class: "btn btn-outline-primary mb-1 btn-sm" %>
    </div> 
  </div>
</div>

app/views/cart/final.html.erb
<h1>Já era</h1>

app/views/cart/last.html.erb
<h1>Acabou-se tudo. Desculpa intão.</h1>

app/views/cart/show.html.erb
<%= turbo_frame_tag "cart" do %>
  <div class="m-3">
    <% if @cart.orderables.count > 0 %>
      <%= render "cart/orderables" %>
    <% else %>
      <p>Nenhum produto.</p>
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<div style="text-align:center; margin: 20px;">
  <h1 class="greeting">Welcome, this is the home page</h1>  
</div>
<div style="margin: 0 auto;">
  <div class="container">
    <%= render partial: "alert" %>  
  </div>
  <div>
    <section class="products">
      <% @products.each do |product| %>
        <a href="<%= url_for(product) %>">
          <div id="productCard" class="product-card" onmouseover="this.classList.add('wiggle');" onmouseout="this.classList.remove('wiggle');">
            <div class="product-image">
              <% if has_img?(product.description) %>
                <%= return_img(product.description) %>
              <% else %>
                <%= image_tag product.images[0], class:"resize" %>
              <% end %>
            </div>
            <div class="product-info">
              <h5><%= product.title %></h5>
              <h6><%= number_to_currency(product.value, unit: "R$ ", separator: ",", delimiter: "") %></h6>
            </div>
          </div>
        </a>
      <% end %>
    </section>
  </div>
</div>
<button type="button" 
class="btn btn-sm btn-danger" 
data-bs-toggle="popover" 
title="Popover title" 
data-bs-content="Amazing content, right ?">
Click to toggle popover
</button>  

<% content_for :javascript do %>

<% end %>

app/views/layouts/_cart_qtty.html.erb
<%= turbo_frame_tag "cart_qtty" do %>
  <% if cart_total > 0 %>
    <li class="nav-item">
      <b class="nav-link active"> <i class="bi bi-cart4"></i> <a href="<%= url_for(cart_path) %>" class="black-link">Carrinho   <span class="badge rounded-pill bg-danger"> <%= cart_total %></span></a></b>
    </li>
  <% end %>    
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'products' %>
    <%= javascript_include_tag 'products' %>

    <%= yield :javascript %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= url_for(root_path) %>"><i class="bi bi-shop"></i> Awesome-Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", root_path, class:"nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Novo produto", new_product_path, class:"nav-link active" %>
            </li>
            
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <div class="d-flex" role="search">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if current_user.nil? %>
                <li class="nav-item">
                  <b class="nav-link active"><i class="bi bi-box-arrow-in-right"></i> <a href="<%= url_for(login_path) %>" class="black-link">Entrar</a></b>
                </li>
                <li class="nav-item">
                  <b class="nav-link active"><i class="bi bi-person-add"></i> <a href="<%= url_for(signup_path) %>" class="black-link">Criar conta</a></b>
                </li>
              <% else %>
                <li class="nav-item">
                  <b class="nav-link active"><i class="bi bi-person-circle"></i> <%= current_user.username %></b>
                </li>
                <li class="nav-item">
                  <b class="nav-link active"> <i class="bi bi-x-circle"></i> <a href="<%= url_for(logout_path) %>" class="black-link">Sair</a></b>
                </li>

                <% if !@cart.nil? %>
                  <%= render partial: "layouts/cart_qtty" %>
                <% end %>

              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <%
=begin%>
 <%= render partial: "cart/cart" if @render_cart %> 
<%
=end%>

    <%= yield %>

    <script>
    $(document).ready(function() {
      $('#notice').delay(2000).fadeOut(2000); // 5 seconds x 1000 milisec = 5000 milisec
    });

    // $(document).ready(function() {
    //   const firstImage = $("#images img:first");
    //   const displayedImage = $("#displayed-image");
    //   displayedImage.attr("src", firstImage.attr("src"));
    // });

    </script>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <div class="m-3 p-3 border shadow white-bkg">
    <%= render partial: "alert" %>
    <div class="m-lg-3">
      <%= form_with model: product, html: { id: 'product-form' } do |f| %>
        <div class="mb-3">
          <%= f.label 'Produto', class: "form-label" %>
          <%= f.text_field :title, placeholder: 'Nome do produto', class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label 'Imagens', class: "form-label" %>
          <%= f.file_field :images, multiple: true, class: "form-control", options: { type: "file" } %>
        </div>
        <div class="mb-3">
          <%= f.label 'Descrição e imagens', class: "form-label" %>
          <%= f.rich_text_area :description %>
        </div>
        <div class="mb-3">
          <%= f.label 'Palavras-chave (somente minúsculas)', class: "form-label" %>
          <%= f.text_field :keywords, placeholder: 'Palavras-chave', class: "form-control" %>
        </div>
        <div class="mb-3 row">
          <%= f.label 'Valor', class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.number_field :value, min: 0, step: 0.01, class: "form-control form-number" %>
          </div>
        </div>
        <div class="mb-3 row">
          <%= f.label 'Valor em promoção', class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.number_field :sale_price, min: 0, step: 0.01, class: "form-control form-number" %>
          </div>
        </div>
        <div class="mb-3">
          <%= f.label 'Em promoção', class: "form-label" %>
          <%= f.check_box :sale, class: "form-check-input" %>
        </div>
        <div class="mb-3 row">
          <%= f.label 'Quantidade em estoque', class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.number_field :stock, class: "form-control form-number" %>
          </div>
        </div>
        <div class="mb-3">
          <%= f.submit "Enviar", class: "btn btn-outline-primary mb-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_image_modal.html.erb
<div id="image-modal" class="modal">
  <div class="modal-content">
  <span class="close-modal">&times;</span>
    <img id="modal-image" src="#">
  </div>
</div>

<script>
const closeModal = document.querySelector(".close-modal");
const imageModal = document.querySelector("#image-modal");

closeModal.addEventListener("click", function () {
  imageModal.style.display = "none";
});
</script>

app/views/products/_product.html.erb
  <div id="<%= dom_id product %>">
    <div style="display:flex;justify-content:space-between; margin: 0em 5em;">
      <%= product.title %>

      <%= product.value %>

      <%= form_with(url: cart_add_path)  do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        
          <%= f.label :quantity, "Quantidade", class: "form-label" %>
          <%= f.number_field :quantity, value: 0, style: "width: 4em;", id: "number_field" %>
        <%= f.submit "Comprar", class: "btn btn-primary mb-3" %>
      <% end %>
    </div>

app/views/products/new.html.erb
<%= render partial: "form", locals: { product: @product } %> 

app/views/products/show.html.erb
<div class="container">
  <div class="row border shadow white-bkg m-lg-3">
    <%= render partial: "alert" %>
    <div class="col-sm-8">
      <div>
        <div class="m-lg-3">
          <div style="text-align:center; margin-bottom:20px;">
            <div id="display-area">
              <img id="displayed-image" class="resize-big">
            </div>
            <% if @product.images %>
              <div class="d-inline-flex flex-wrap" id="images">
                <% @product.images.each do |image| %>
                  <div>
                    <%= image_tag(image, class:"resize-sml img-cursor", onclick: "displayImage(this);") %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
          <%= @product.description %>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div>
        <div class="m-lg-3">
          <H1 class="product-title"><%= @product.title %></H1>
          <div class="show-value">
            <%= number_to_currency(@product.value, unit: "R$ ", separator: ",", delimiter: "") %>
          </div>
          <div>
          Em estoque: <%= @product.stock %>
          </div>
          
          <div style="margin-top:20px;">
            <%= form_with(url: cart_add_path) do |f| %>
              <%= f.hidden_field :id, value: @product.id %>
              <%= f.hidden_field :from, value: 1 %>
              <div class="form-group" style="margin-bottom:10px;">
                <%= f.label :quantity, "Quantidade", class: "form-label" %>
                <button type="button" onclick="decrementNum()" id="decrease_button" class="clean-button">-</button>
                <%= f.number_field :quantity, value: 1, style: "width: 4em;", id: "number_field" %>
                <button type="button" onclick="incrementNum()" id="increase_button" class="clean-button">+</button>
              </div>
              <div class="actions"><%= f.submit "Comprar", class: "btn btn-primary mb-3" %></div>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {
      const firstImage = $("#images img:first");
      const displayedImage = $("#displayed-image");
      displayedImage.attr("src", firstImage.attr("src"));
    });



function displayImage(image) {
  const displayedImage = document.querySelector("#displayed-image");
  displayedImage.src = image.src;
}

  function incrementNum() {
    var numberField = document.getElementById("number_field")
    let currentValue = parseInt(numberField.value);
    numberField.value = currentValue + 1;
  };

  function decrementNum() {
    var numberField = document.getElementById("number_field")
    let currentValue = parseInt(numberField.value);
    if (currentValue > 1) { 
      numberField.value = currentValue - 1;
    }
  };

</script>

app/views/products/show.html.modal.erb
<div class="container">
  <div class="row border shadow white-bkg m-lg-3">
    <%= render partial: "alert" %>
    <div class="col-sm-8">
      <div>
        <div class="m-lg-3">

          <div id="image-modal" class="modal">
            <span class="close-modal">&times;</span>
            <img id="modal-image" class="modal-content">
          </div>

          <%= @product.description %>
          
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div>
        <div class="m-lg-3">
          <H1><%= @product.title %></H1>
          <div class="show-value">
            <%= number_to_currency(@product.value, unit: "R$ ", separator: ",", delimiter: "") %>
          </div>
          <% if @product.images %>
            <div class="d-inline-flex flex-wrap">
              <% @product.images.each do |image| %>
                <div>
                  <%= link_to image_tag(image, class:"resize-sml"), "#", class: "open-modal", onclick: "openModal(event);" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

const closeModal = document.querySelector(".close-modal");
const imageModal = document.querySelector("#image-modal");

closeModal.addEventListener("click", function () {
  imageModal.style.display = "none";
});


function openModal(event) {
  event.preventDefault();
  const link = event.target.closest("a");
  const modalImage = document.querySelector("#modal-image");
  modalImage.src = link.querySelector("img").src;
  document.querySelector("#image-modal").style.display = "block";
}

</script>

app/views/users/_form.html.erb
<div class="container">
  <div class="p-3 my-3 border shadow white-bkg mx-auto" style="width:300px;">
    <%= render partial: "alert" %>
      <h3>Conta</h3>
      <%= form_for user do |f| %>
        <% if user.errors.any? %>
          <div id="notice" class="alert alert-dismissible alert-warning">
            <h3>Atenção:</h3>
            <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>

        <div class="mb-3">
          <%= f.label 'Usuário', class: "form-label" %>
          <%= f.text_field :username, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label 'Email', class: "form-label" %>
            <%= f.text_field :email, class: "form-control" %>
        </div>
    
        <div class="mb-3">
            <%= f.label 'Senha', class: "form-label" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label 'Repita a senha', class: "form-label" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.submit "Enviar", class: "btn btn-outline-primary mb-3" %>
        </div>
      <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render partial: "form", locals: { user: @user } %>